name: PlantUML Diagrams

on:
  push:
    branches:
      - main
      - warmhouse
  pull_request:
    branches:
      - main
      - warmhouse

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download PlantUML jar
        run: curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar

      - name: Generate Diagrams
        run: |
          mkdir -p out
          java -jar plantuml.jar -o out diagrams/smart-home-monolith/context/*.puml

      - name: Commit Diagrams
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add diagrams/**/*.png out/**/*.png
          git diff --cached --quiet || git commit -m "Automated diagram generation"
          git push origin HEAD
        if: success()
